import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    catalogo_carrosel:[
        {
            id:'',
            img:'',
        },
        {
            id:'',
            img:'',
        },
        {
            id:'',
            img:'',
        },
        {
            id:'',
            img:'',
        },
        {
            id:'',
            img:'',
        }
    ],
    promocoes_relampago:[
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        }
    ],
    produtos_mais_vendidos:[
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        }
    ],
    destaques:[
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        },
        {
            id:'',
            img:'',
            descricao:'',
            preço_original:0,
            desconto:0,
            n_parcelas_sem_juros:0,
            parcelas_com_juros:0,
            tempo:0
        }
    ]
}

export const homepageSlice = createSlice({
  name: 'homepage',
  initialState,
  reducers: {
    setPath: (state, action) => {
      state.path = action.payload;
    },
  },
});


export const {setPath} = homepageSlice.actions;

export default homepageSlice.reducer;